# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171113_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='logo',
        ),
    ]
